wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: UNet
dataset:
  desc: null
  value: your_dataset_name
epochs:
  desc: null
  value: 800000
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725809111
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
